FROM php:8.0-apache

# Instalar dependencias y limpiar caché
RUN apt-get update \
    && apt-get install -y libpq-dev libpng-dev libjpeg62-turbo-dev libyaml-dev tzdata \
    && ln -snf /usr/share/zoneinfo/America/Asuncion /etc/localtime \
    && echo "America/Asuncion" > /etc/timezone \
    && pecl install yaml \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get autoremove -y

# Configurar y habilitar extensiones de PHP
RUN docker-php-ext-configure gd \
    && docker-php-ext-install pgsql pdo_pgsql gd \
    && docker-php-ext-enable yaml

# Configurar tamaño máximo de archivo para subidas
RUN echo "upload_max_filesize = 10M;" > /usr/local/etc/php/conf.d/uploads.ini

# Configurar zona horaria de PHP
RUN echo "date.timezone=America/Asuncion" > /usr/local/etc/php/conf.d/timezone.ini

# Habilitar el módulo rewrite de Apache y reiniciar
RUN a2enmod rewrite \
    && service apache2 restart
